### ISSUE TITLE
Cellphone DB

### ISSUE THREAD

**Issue by zara03** [ventolab/CellphoneDB#100]
Hi 
i am able to have fig for interaction among different cell types ;ike T Cells ,Hepatocytes etc but i want to know if i want to highligt interaction more than a number suppose 70 how to change colour of line making it red as in fig attached.
I want to make a fig like this
![Screen Shot 2023-03-28 at 10 18 10 AM](https://user-images.githubusercontent.com/96392364/228269509-9044ff50-cb59-4910-9b95-64907dd0d958.png)

**Comment by luzgaral** [comment]
Hi @zara03 

Thank you for using cellphoneDB.

Apologies but CellphoneDB package does not cover this type of visualisation. To visualise graphs, you can use R/python libraries such igraph or specialised software like Cytoscape.

Hope this help,

Best,

Luz
