### ISSUE TITLE
Number of interactions between 2 different cell types

### ISSUE THREAD

**Issue by zara03** [ventolab/CellphoneDB#107]
Hi
I am trying to understand the package.
I am trying to extract total number of interactions between different cell types.
Like what i did was:
### C <- netVisual_chord_gene(cellchat, sources.use = c("Cholangiocytes"), targets.use = c("Cholangiocytes","Mesencyme,"Neutrophils"),legend.pos.x = 10,legend.pos.
<img width="1272" alt="Screen Shot 2023-04-16 at 4 31 03 PM" src="https://user-images.githubusercontent.com/96392364/232340416-6b6d580c-4190-40b6-861d-558cebd3ce65.png">
y = 10)

and i got chord diagram but i want to know quantitative number of interactions?How to extract that?
When i am opening "C" which is object that has these interaction it comes like the image i attached.i am unable to see total or number of interactions?
Kindly guide.

**Comment by prete** [comment]
Hi @zara03 I think you're using CellChat and this is the **CellPhoneDB** repository. 
May be better to open an issue on that tool's repo https://github.com/sqjin/CellChat/issues 

For what it's worth, the returned object for `netVisual_chord_gene` is a `recordedplot` object, so I doubt it has the info you're looking for. Possibly you'll get a better undersatinding but looking at that function's source code https://rdrr.io/github/sqjin/CellChat/src/R/visualization.R

**Comment by zara03** [comment]
Thank you so much. I am trying to understand meanwhile i have posted on tools repo.
