### ISSUE TITLE
latest scikit-learn

### ISSUE THREAD

**Issue by wangjiawen2013** [ventolab/CellphoneDB#108]
Hi,
cellphonedb uses scikit-learn==0.24, while the latest  scikit-learn is version 1.2.2, hope cellphonedb can support the latest scikit-learn to improve it's compatibility, because most packages in our environment use the latest one now.

**Comment by ktroule** [comment]
Thanks for the suggestion.

We recommend installing CellPhoneDB in a different environment.

**Comment by thisisamirv** [comment]
Come on guys please update CellPhoneDB codes to support the latest scikit-learn. I don't want to use conda

**Comment by thisisamirv** [comment]
You are not even using the scikit-learn package anywhere in the code

**Comment by thisisamirv** [comment]
Thanks great
