### ISSUE TITLE
hierarchical comparsions

### ISSUE THREAD

**Issue by wangjiawen2013** [ventolab/CellphoneDB#111]
Hi,
The following were excerpted from  cellphonedb's documentation:
 METHOD 3 degs_analysis (>= v3): This method is proposed as an alternative to the statistical inference approach. This approach allows the user to design more complex comparisons to retrieve interactions specific to a cell type of interest. This is particularly relevant when your research question goes beyond comparing “one” cell type vs “the rest”. Examples of alternative contrasts are hierarchical comparisons (e.g. you are interested in a specific lineage, such epithelial cells, and wish to identify the genes changing their expression within this lineage).

Could you explain what is "hierarchical comparisons", I cannot find literatures on this term. Is it related to hierarchical clustering ?

**Comment by luzgaral** [comment]
Hi @wangjiawen2013 ,

By hierarchical comparison we refer to any comparison between clusters that can be organised by a hierarchy or groups. Hierarchical clustering could be a potential way of organising your clusters, but here we refer to a more general and simple classification.

An example when you may have your clusters organised by groups/hierarchy is the following: imagine that you have three cell types (A, B and C) which states change between two conditions (health and disease): A-healthy, A-disease, B-healthy, B-disease, C-healthy, C-disease. **Depending on your research question**, you might wish to group (and compare) your cells as healthy(A,B,C) & disease(A,B,C) or A(healthy,disease) B(healthy,disease) & C(healthy,disease). 
- Scenario 1, you are interested on how A changes between healthy and disease, you then compare A-healthy vs A-disease. 
- Scenario 2, you are interested on how A-B-C change within the disease group only. Here you compare A-disease vs B-disease vs C-disease. 
- Scenario 3, you are interested on what is specific to any cluster, independently on any hierarchy/grouping.  Here you then compare A-healthy vs rest (A-disease + B-healthy + B-disease + C-healthy + C-disease), etc.


With CellphoneDB method 3 relying on differentially expressed genes, the user can organise their comparisons in a more complex way (like scenarios 1-2). CellphoneDB method 2 would instead perform scenario 3 and compare one vs all the rest.

Hope this helps.

Best

Luz
