### ISSUE TITLE
KeyError: 'gene_synonym_to_gene_name'

### ISSUE THREAD

**Issue by YinCY123** [ventolab/CellphoneDB#113]
Hello, thanks for this great package!

I'm now try to use this package for my single cell data, but when I'm running the example of cpdb_statistical_analysis_method, there rise the following error.  How can i fix it?

from cellphonedb.src.core.methods import cpdb_statistical_analysis_method

deconvoluted, means, pvalue, significant_means = cpdb_statistical_analysis_method.call(
    cpdb_file_path = "/home/yincy/git/data/cellphonedb/v4.0.0/cellphonedb_v4.0.0.zip",
    meta_file_path = "../github/CellphoneDB/example_data/test_meta.txt",
    counts_file_path = "../github/CellphoneDB/example_data/test_counts.txt",
    counts_data = "ensembl",
    output_path = "/home/yincy/git/mouse-kidney/cpdb_outs/",
    threshold = 0.1,
    threads = 4
)

KeyError                                  Traceback (most recent call last)
Cell In[3], line 3
      1 from cellphonedb.src.core.methods import cpdb_statistical_analysis_method
----> 3 deconvoluted, means, pvalue, significant_means = cpdb_statistical_analysis_method.call(
      4     cpdb_file_path = "/home/yincy/git/data/cellphonedb/v4.0.0/cellphonedb_v4.0.0.zip",
      5     meta_file_path = "../github/CellphoneDB/example_data/test_meta.txt",
      6     counts_file_path = "../github/CellphoneDB/example_data/test_counts.txt",
      7     counts_data = "ensembl",
      8     output_path = "/home/yincy/git/mouse-kidney/cpdb_outs/",
      9     threshold = 0.1,
     10     threads = 4
     11 )

File ~/venvs/biopy/lib/python3.9/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_method.py:95, in call(cpdb_file_path, meta_file_path, counts_file_path, counts_data, output_path, microenvs_file_path, iterations, threshold, threads, debug_seed, result_precision, pvalue, subsampling, subsampling_log, subsampling_num_pc, subsampling_num_cells, separator, debug, output_suffix)
     90     raise MissingRequiredArgumentsException(description="All of the following arguments need to be provided: {}".format( \
     91     "cpdb_file_path, meta_file_path, counts_file_path, counts_data, output_path"))
     93 # Load into memory CellphoneDB data
     94 interactions, genes, complex_composition, complex_expanded, gene_synonym2gene_name = \
---> 95     db_utils.get_interactions_genes_complex(cpdb_file_path)
     97 # Load user files into memory
     98 counts, meta, microenvs, degs = file_utils.get_user_files( \
     99     counts_fp=counts_file_path, meta_fp=meta_file_path, microenvs_fp=microenvs_file_path, \
    100     gene_synonym2gene_name=gene_synonym2gene_name, counts_data=counts_data)

File ~/venvs/biopy/lib/python3.9/site-packages/cellphonedb/utils/db_utils.py:46, in get_interactions_genes_complex(cpdb_file_path)
     43 dbTableDFs = extract_dataframes_from_db(cpdb_file_path)
     44 # Convert dbTableDFs into interactions, genes, complex_composition, complex_expanded data frames
     45 # and gene_synonym2gene_name dict
---> 46 gs2gn = dbTableDFs['gene_synonym_to_gene_name']
     47 gene_synonym2gene_name = dict(zip(gs2gn['Gene Synonym'], gs2gn['Gene Name']))
     49 mtTable = dbTableDFs['multidata_table']

KeyError: 'gene_synonym_to_gene_name'

**Comment by ktroule** [comment]
Hi,

A couple of checks to understand your issue.

1) Are you using mice id as input?
2) Have you converted the database to match your mouse ids to the human ids in the database?
3) Do you have the source files in the same folder where you have the database zip?

Thanks

**Comment by YinCY123** [comment]
Actually, I'm running `statistical_analysis_method` with the sample data located in the Ventolab/CellPhonedb/example_data/. Those files have the right human ids in the database.

But I'm not sure if the database zip file is correct. I download the five database files and zip those files into a folder.

**Comment by ktroule** [comment]
In order to download the database check this [notebook](https://github.com/ventolab/CellphoneDB/blob/master/notebooks/T00_DownloadDB.ipynb).

**Comment by YinCY123** [comment]
Thank you for your help, the problem has been solved, it is the database's problem.
