### ISSUE TITLE
Adding my own ligand-receptor pair to CellphoneDB

### ISSUE THREAD

**Issue by biotech25** [ventolab/CellphoneDB#114]
I'd like to add my own ligand-receptor pair to CellphoneDB.   

I checked the CellphoneDB v4 database (https://github.com/ventolab/cellphonedb-data/tree/master/data) files, such as 'complex_input.csv', 'gene_input.csv', 'interaction_input.csv', 'protein_input.csv'.  But, it seems that there are no ligand-receptor pair that I want to see in my count input data.  Then, which file should I add my own ligand-receptor information to?  Should I add my own ligand-receptor information to the all 4 files?   Could you give me some explanation?  

Thank you, 
Sanghoon

**Comment by ktroule** [comment]
Hi,

You will find detailed information regarding the tables in the CellPhoneDB [manuscript](https://www.nature.com/articles/s41596-020-0292-x). 

In short, you have to add your interactions to the `interaction_input.csv`, if you add a protein or complex not present in the database those will also need to be added to either the complex or protein table.

Regards
Kevin

**Comment by ktroule** [comment]
You should be able to use your previous db with the new CellPhoneDB implementation with minor modifications.  Note that we have added a few extra columns to the `interaction_input.csv` and you need also need a new `sources` folder in the same directory where the database is.

Check notebooks with prefix `T00` to download and create your database [here](https://github.com/ventolab/CellphoneDB/tree/master/notebooks).

**Comment by biotech25** [comment]
Thank you for your kind explanation. I will follow your instruction, and come back to you if I have more questions.  Thank you for your help!
