### ISSUE TITLE
Application condition 

### ISSUE THREAD

**Issue by LuShuYangMing** [ventolab/CellphoneDB#117]
Is it suitable for tranditional bulk RNAseq ? For example, group A, group B ...., each group have two cell types (T and macrophages) with five replicates.

**Comment by ktroule** [comment]
Hi.

Technically you can use CellPhoneDB, biologically it would depend on your specific question.
You can infer cell interactions between groups but cell types will be cofounded due to the nature of bulk RNAseq.
