### ISSUE TITLE
Pvalue adjusting

### ISSUE THREAD

**Issue by maximelepetit** [ventolab/CellphoneDB#121]
Hi.

Is there any p-value correction steps, e.g, Bonferroni or BH, included before reporting the p-value? 

Best regards !

**Comment by ktroule** [comment]
Hi, thanks for using CellPhoneDB.

No, P-values are uncorrected.

Regards

**Comment by MarieCoutelier** [comment]
Hi, 
We were wondering if you would recommend to correct the p-values then? And if so, how? 
Thanks, 
Marie

**Comment by datasome** [comment]
Hi Marie,

The authors of the package are not available to comment for the time being, but I understand an advice from a statistician was sought in the past and the recommendation was not to correct p-values. I'm afraid I'm not able to offer any more advice than this. 

Best,
Robert.

**Comment by MarieCoutelier** [comment]
Hi Robert, 
Thanks a lot for your input ! Do you know if the recommendation comes from the fact that the permutation method accounts for multiple testing already? 
All the best,
Marie

**Comment by MarieCoutelier** [comment]
Dear Robert, 

My apologies for my late reply.
I just wanted to thank you for your insightful comments, they were really useful for us to decide on an analysis strategy. 

In the end, we decided to apply a BH correction per celltype-couple; it does not reduce much the amount of significant interactions, but we feel more confident with more stringent results. 

All the best, 

Marie

**Comment by datasome** [comment]
Hi Marie,

Glad to hear that you found those helpful and thank you for letting me know. I wish you best of luck in your research.

Best wishes,

Robert.
