### ISSUE TITLE
Question about method 2 mean calculation for interactions containing complex partner

### ISSUE THREAD

**Issue by stanaka6** [ventolab/CellphoneDB#123]
Hello,

Thank you so much for developing a great tool! 

I have a question about the method2 outputs, especially the "means" output. Could you please explain how means are calculated for the interactions containing complex partners?

For example, 

- CPI-SC00D19A858: BMP6_BMPR1A_BMPR2
- CPI-SC00DF87C38: BMP6_ACVR1_BMPR2
...

If I understand correctly, the mean is the total mean of each partner's average expressions. If the above example CPI-SC00D19A858, the mean value in means.txt output from method2 is total expressions of three genes' average expressions (BMP6 in cell type A, BMPR1A in cell type B, BMPR2 in cell type B)? 

I might misunderstand something, but I would be grateful if you could provide me with some clarification for this point. 

Thank you very much!

**Comment by luzgaral** [comment]
Hi @stanaka6 

Thank you for using cellphoneDB.

How mean is computed is described in the [documentation](https://cellphonedb.readthedocs.io/en/latest/RESULTS-DOCUMENTATION.html#method-1-retrieval-of-interaction-expression-means) and the [protocols paper](https://www.nature.com/articles/s41596-020-0292-x).
"To compute the mean of an interaction involving multi-subunit heteromeric complexes we use the member of the complex with the minimum expression." 

In the examples above,  the mean value in means.txt output from **any method** is total expressions of **two** genes' average expressions (BMP6 and min[BMPR1A, BMPR2] ).

Hope this helps,

Luz
