### ISSUE TITLE
About the pvalue.txt result

### ISSUE THREAD

**Issue by SZ-qing** [ventolab/CellphoneDB#124]
Hi, I see it described in the pvalue result for method2 in the notebook as, `cell_a|cell_b: 1 if interaction is detected as significant, 0 if not.`
But, in real output pvalue.txt result, contains values that are neither 0 nor 1. Is the value for the paired cell types in the pvalue.txt file the real p-value, or is it after processing based on the threshold？
Also, I saw that the **pvaule.txt** file was processed in the **ktplot-py** code, and found that the result of the pvalue was treated as the real pvalue. i'm a bit confused now

**Comment by SZ-qing** [comment]
The notebook web site: https://github.com/ventolab/CellphoneDB/blob/master/notebooks/T01_Method2_with_subsampling.ipynb

and the ktplot-py code: https://github.com/zktuong/ktplotspy/blob/master/ktplotspy/plot/plot_cpdb.py   **line 263**

**Comment by ktroule** [comment]
Hi.

This is indeed wrong, this file contains the p-values derived from the random shuffling.
I've modified the notebook.

Thanks for noting the error.
