### ISSUE TITLE
OSError on windows

### ISSUE THREAD

**Issue by rocketeer1998** [ventolab/CellphoneDB#127]
Hi @kant , thanks for your contribution to cellphonedb! I successfully downloaded it on windows10, however, i was stuck on the file outputting stage, because an OSError: [Errno 22] occured, which said, `OSError: [Errno 22] Invalid argument: 'D:/SEERNA/20230710_MoWei/example\\statistical_analysis_deconvoluted_07_11_2023_11:33:37.txt'
`. I've tested it both on example datasets and my datasets, but all failed at this stage. It seems that your team has fixed it on issue #102 and updated cellphonedb.

**Comment by datasome** [comment]
Hi Rocketeer1998,
A similar problem was reported before and I made a fix for it - see: https://github.com/ventolab/CellphoneDB/issues/102#issuecomment-1507100147 
Please could you do "pip install --force-reinstall "git+https://github.com/ventolab/CellphoneDB.git" and try again?
Thanks and good luck!
Robert.

**Comment by lichen2018** [comment]
> 

Dear datasome,
I've met the same problem after running "pip install --force-reinstall "git+https://github.com/ventolab/CellphoneDB.git" as shown below.
Code:
means, deconvoluted = cpdb_analysis_method.call(
    cpdb_file_path = cpdb_file_path,           # mandatory: CellPhoneDB database zip file.
    meta_file_path = meta_file_path,           # mandatory: tsv file defining barcodes to cell label.
    counts_file_path = counts_file_path,       # mandatory: normalized count matrix.
    counts_data = 'hgnc_symbol',               # defines the gene annotation in counts matrix.
    output_path = out_path,                    # Path to save results    microenvs_file_path = None,
    separator = '|',                           # Sets the string to employ to separate cells in the results dataframes "cellA|CellB".
    threshold = 0.1,                           # defines the min % of cells expressing a gene for this to be employed in the analysis.
    result_precision = 3,                      # Sets the rounding for the mean values in significan_means.
    debug = False,                             # Saves all intermediate tables emplyed during the analysis in pkl format.
    output_suffix = None                       # Replaces the timestamp in the output files by a user defined string in the  (default: None)
)


Error: handle = open(
    857             handle,
    858             ioargs.mode,
    859             encoding=ioargs.encoding,
    860             errors=errors,
    861             newline="",
    862         )
    863     else:
    864         # Binary mode
    865         handle = open(handle, ioargs.mode)

OSError: [Errno 22] Invalid argument: 'D:\\Data\\debug\\cellphonedb\\ob\\simple_analysis_means_result_07_11_2023_23:34:59.txt'

**Comment by datasome** [comment]
Hi rocketeer1998,
I would suggest doing "pip install --force-reinstall "git+https://github.com/ventolab/CellphoneDB.git" in a clean venv - the suffix format is now %m_%d_%Y_%H%M%S - hence you must still be using the version you installed from PyPI.
Hope that helps,
Robert.

**Comment by rocketeer1998** [comment]
It works now, thanks a lot!
