### ISSUE TITLE
Subsetting dotplot

### ISSUE THREAD

**Issue by monikaramos** [ventolab/CellphoneDB#13]
Hello,

Can someone please provide information regarding the possibility of subsetting the dotplot output. Perhaps to any interactions with p value less than 0.05. 

Also, I tried to subset my means.txt and pvalues.txt to signaling pathways/interactions that are not inflated to reduce the output and made sure the same contents were in both the means.txt and pvalues.txt after subsetting however now when I run plot dot_plot on these files i get the following error: 

(cpdb) [mramos@hbl23 cellphonedb]$ cellphonedb plot dot_plot --means-path means_subset.txt --pvalues-path subsetted_sig_pvalues.txt
R[write to console]: Error in `[.data.frame`(all_means, match(selected_rows, intr_pairs), selected_columns) :
  undefined columns selected

[ ][APP][31/01/22-15:45:56][ERROR] R Runtime Exception: Error in `[.data.frame`(all_means, match(selected_rows, intr_pairs), selected_columns) :
  undefined columns selected

Any ideas?

**Comment by luzgaral** [comment]
Hi, 

Currently you can subset the dotplot to specific cell types or L/R as described [here](https://github.com/ventolab/CellphoneDB#dot_plot)

When running `cellphonedb plot dot_plot --rows in/rows.txt --columns in/columns.txt`

You can generate `--rows in/rows.txt` by selecting the interactions with p value less than 0.05 in a combination of cell types of interest.

Hope this helps,

Luz

**Comment by monikaramos** [comment]
@luzgaral Thanks for the response. 

For the --columns argument, I could use this to have a dot plot of specified cell-cell interactions correct? If yes, what output file from running cpdb do I retrieve the cell type-cell type column names from to then list in the .txt file? 

Also, is the txt file only to be one column with the cell types to be plotted as a list format in one column?

Thanks for the help.

**Comment by monikaramos** [comment]
Hi @luzgaral Thank you for the reply! I appreciate the help. I supplied a columns.txt file to only plot the cell cell interactions of interest but I see that there are still a bunch of nonstatistically significant interacting pairs listed on the y axis. I understand I would also need to provide a rows.txt to select interactions with pvalue less than 0.05 but how do you go about doing this in excel for example aside from a manual removal ?

**Comment by luzgaral** [comment]
Hi,

Apologies, I'm not familiar with excel. It should be easy and quick to parse large tables with R or python.

Best wishes,

Luz
