### ISSUE TITLE
error in analysis

### ISSUE THREAD

**Issue by harshagr21** [ventolab/CellphoneDB#131]
hi,
while uploading count matrix and meta file i am getting this error.
can you help me?
![image](https://github.com/ventolab/CellphoneDB/assets/133910547/73678d6b-267c-4a42-8b72-1eaaf1a91d4f)

**Comment by datasome** [comment]
Hi @harshagr21 ,

Please take a look at https://github.com/ventolab/CellphoneDB/issues/18 - could it be that your adata.obs.index has duplicated values? Hope this helps.

Best,

Robert.

**Comment by harshagr21** [comment]
Hi,
thanks for the reply yes it was the same problem, i fixed it.
