### ISSUE TITLE
error in result saving

### ISSUE THREAD

**Issue by harshagr21** [ventolab/CellphoneDB#132]
hi,
i am facing error in saving file to the output path.
i am using windows is it cause of it.
can you help me please.

![image](https://github.com/ventolab/CellphoneDB/assets/133910547/7e4db7f0-2874-4ff7-a4cd-58660e606a1f)

**Comment by datasome** [comment]
Hi @harshagr21,

Please take a look at https://github.com/orgs/pyinstaller/discussions/5468 to see if that helps. It is unlikely to be the problem in CellphoneDB running on Windows, but permissions issue with your 'results' folder. Let me know how yo get on.
Best,

Robert.
