### ISSUE TITLE
Error in building DB for v3.0.0

### ISSUE THREAD

**Issue by avsarg** [ventolab/CellphoneDB#133]
Hi all and CellPhoneDB team,

I want to run statistical method with **CellPhoneDB v3**. But, because there is no cellphonedb.zip for v3.0.0, I downloaded the files for it with “T00_DownloadDB” and copied the “sources” document from v4.1.0. Hence, I have all required files to run the “T00_BuildDBFromFiles” notebook. However, when I run the code (_db_utils.create_db(cpdb_input_dir)_),  I got the error below. As far as I saw, the 'uniprot_5' column is missed in complex_input.csv.

KeyError: "['version', 'uniprot_5'] not in index"

Can you help to build the cellphonedb.zip file for v3?

Thanks,

**Comment by datasome** [comment]
Dear Gülben,
Please accept our apologies - we may have omitted to say in our documentation that the .zip format of our latest database is compatible with CellPhoneDB package versions 4.0 or greater. We will add this information to our documentation before the next package and data release planned for this autumn.
If you wish to use cellphonedb.zip v4.1.0 (or build your own), we recommend that you upgrade your CellPhoneDB package to v4.0.0.
Please accept our apologies for the inconvenience and good luck with your analysis!
Best,
Robert.

**Comment by avsarg** [comment]
Hi Robert,

Thanks for your reply. I modified the complex_input.csv file as you recommended, and It is worked :)

Best,

**Comment by avsarg** [comment]
Hi again!

In the above message, I said it`s worked, but (unfortunately) it worked for only **_complex_input.csv_** file :/
Now it gives the error for “**is_ppi**” column in **_interaction_input.csv_** file. How can I fill this column, where is it based on?

Thanks in advance.

**Comment by ktroule** [comment]
`is_ppi` can be filled with boolean characters TRUE/FALSE.
