### ISSUE TITLE
db_utils.download_database produces incompatible files for v3.0.0 and v4.0.0

### ISSUE THREAD

**Issue by sisterdot** [ventolab/CellphoneDB#136]
cool update for the cellphonedb tool and db!

for backwards-compatibility we wanted to use the v3.0.0 and v4.0.0 dbs...

we used db_utils.download_database to download both db versions:

which downloads the following files for v3.0.0 
Downloaded complex_input.csv into cellphonedb_databases/v3.0.0
Downloaded gene_input.csv into cellphonedb_databases/v3.0.0
Downloaded gene_input_all.csv into cellphonedb_databases/v3.0.0
Downloaded interaction_input.csv into cellphonedb_databases/v3.0.0
Downloaded protein_input.csv into cellphonedb_databases/v3.0.0

and for 4.0.0
Downloaded complex_input.csv into cellphonedb_databases/v4.0.0
Downloaded gene_input.csv into cellphonedb_databases/v4.0.0
Downloaded gene_input_all.csv into cellphonedb_databases/v4.0.0
Downloaded interaction_input.csv into cellphonedb_databases/v4.0.0
Downloaded protein_input.csv into cellphonedb_databases/v4.0.0

these are incompatible it seems with the analyses functions of CellPhoneDB 4.0
(cpdb_analysis_method.call and cpdb_statistical_analysis_method.call)

first complaint was that cellphonedb.zip is missing, but even after zipping all the files, other files are missing like gene_synonym_to_gene_name or multidata_table.csv 

any way to be backwards compatible with old dbs when using [https://pypi.org/project/CellphoneDB/4.0.0](https://pypi.org/project/CellphoneDB/4.0.0/) ?

thank you

**Comment by ktroule** [comment]
Hi.

We currently do not have DB v4 and v3 in the format required by the latest version of the tool.
You can download the DB v4.0.1 and use the newly added files to build v3 a d v4 db.
Note, that newer versions of the DB contain more columns, hence you will need to add them manuall.y

Check this [issue](https://github.com/ventolab/CellphoneDB/issues/133#event-9972787379).
