### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Ithinky** [ventolab/CellphoneDB#139]
Hi, thanks for your great tool !

I created a conda environment with python=3.10.12, and excuted pip install cellphonedv==4, but the scikit-learn can't be downloaded, just like the following:

  **note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects**

I have tried to download scikit-learn alone use pip, but the lateste version 1.3.0 can be downloaded while the version 0.24 can't.

Could  you give me some advice, thanks!

**Comment by ktroule** [comment]
Hi.

To install the latest version of the tool please refer to what's described on the main page of the repository.
1. Install it in a new conda environment.
2. Use `pip install cellphonedb`

Try this should work. Moreover, can you provide the operative system in which you are trying this?

Kind regards

**Comment by Ithinky** [comment]
Hi, ktroule
I use centos, and your advice worked! Thank you very much!
Best,
Ithinky
