### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by hemantgujar** [ventolab/CellphoneDB#142]
Hi 

Can someone please help with following issue. 

Thanks 

`pip3 install cellphonedb`

...

Using cached fonttools-4.42.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
Using cached kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for scikit-learn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [796 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

      INFO: C compiler: gcc -pthread -B /home/ec2-user/anaconda3/envs/cpdb/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/ec2-user/anaconda3/envs/cpdb/include -fPIC -O2 -isystem /home/ec2-user/anaconda3/envs/cpdb/include -fPIC

...

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

`python --version`
Python 3.10.13

OS: Red Hat Enterprise Linux with High Availability

**Comment by datasome** [comment]
Hi hemantgujar,

Are you trying to install CellphoneDB into a clean virtual environment? If not, please see https://cellphonedb.readthedocs.io/en/latest/RESULTS-DOCUMENTATION.html#installation for more information. 

Best,

Robert.

**Comment by hemantgujar** [comment]
yes. thanks. that's ok. i was able to install using github file. for some reason pip3 install cellphonedb was not working for me.
