### ISSUE TITLE
Clarification Needed on --threshold Argument

### ISSUE THREAD

**Issue by macelik** [ventolab/CellphoneDB#145]
Hello, 

I have a clarification question about the `--threshold` argument. The documentation states that it represents a percentage of cells, but in the tutorial, it seems to be treated as a fraction. Could you clarify whether setting the threshold to 0.1 means 0.1% or 10%? 

Thank you,
Muhammet

**Comment by datasome** [comment]
Hi Muhammet,
Thank you for using CellphoneDB. 
In https://cellphonedb.readthedocs.io/en/latest/RESULTS-DOCUMENTATION.html#analysis-methods please see the following:

_1. all the genes in the interaction are expressed in the corresponding cell type by more than 10% of cells (threshold = 0.1)_ 

That is threshold = 0.1 corresponds to/means 10% of cells. Hope that helps.

Best,

Robert.

**Comment by macelik** [comment]
Thank you for clearing that up. This resolves the confusion on my side, so I'm closing it now. I appreciate the prompt response.
