### ISSUE TITLE
cellphonedb install problem

### ISSUE THREAD

**Issue by wrfokokokwrf** [ventolab/CellphoneDB#147]
hello，
I have some questions. I installed cellphonedb on Ubuntu using the 'pip install cellphonedb' command. I can import the cellphonedb package on Python and see that it is version 4.0.0.
![2](https://github.com/ventolab/CellphoneDB/assets/105401910/363a9f33-2f7c-473a-b02b-7b18496f7741)
But I entered cellphonedb on the shell command line,but show "cellphonedb：command not found"
how can I deal with this problem.I want to execute cellphonedb on the shell
![image](https://github.com/ventolab/CellphoneDB/assets/105401910/8536189c-f83a-4092-a741-197d76d43118)

Thank you.

**Comment by datasome** [comment]
Hi wrfokokokwrf,

Apologies for not replying earlier - in CellphoneDB v4.0.0 we have moved to Jupyter notebook-based analyses - links to tutorials are available on https://cellphonedb.readthedocs.io/en/latest/RESULTS-DOCUMENTATION.html#novel-features-in-v4. Hope that helps.

Best, 

Robert.
