### ISSUE TITLE
deconvoluted?

### ISSUE THREAD

**Issue by NMalhi92** [ventolab/CellphoneDB#15]
Hi, 

Thank you so much for creating such a useful tool. I have a stupid question if you wouldn't mind helping me. 
I am searching for a particular ligand receptor interaction in my dataset and it was not appearing in the significant means/dot plot, thus I assumed it was not occuring often enough to be captured. However, when I searched the deconvoluted sheet, my receptor of interest (TREM2) is there and the complex_name its associated with does come up in the significant means.csv (PlexinA1_complex1) but has two different genes with it (SEMA6D and NFY4)? I'm just not too sure how to interpret these results?

Thank you,
Nas

**Comment by NMalhi92** [comment]
Does this mean that the ligand is interacting with a complex? i.e. in this case its the ligand SEMA6D interacting with TREM2 within a complex with TYROBP/PLEXINA1?

**Comment by luzgaral** [comment]
Hi Nas,

I'm not sure I follow your question.
deconvoluted file contains all the interactions, not only the significant. Interactions in the deconvoluted file that are not in the significant file are not significant.

Best,

Luz
