### ISSUE TITLE
Relevance score in CPDB

### ISSUE THREAD

**Issue by Pedramto89** [ventolab/CellphoneDB#151]
I did the analysis for PPI via CPDB. Now, I see the 'Relevance' score in the output. As far as I know, it refers to the statistically significant interactions (adj_p_val <0.05) and it should be equal to 1 (Relevance ==1) to filter the output only for significant interactions. However, I have this column in my data and the range of the scores vary from 0.01 for example to 45. What does it mean and how can I interpret the 'Relevance' values?

**Comment by datasome** [comment]
Hi Pedramto89,

Thank you for using CellphoneDB and for your inquiry. 

Please correct me if I'm wrong, but assuming you're using CellphoneDB package v5.0.0 and referring to the output file statistical_analysis_interaction_scores_*.txt? If so, the documentation for the method to calculate these scores is [here](https://cellphonedb.readthedocs.io/en/latest/RESULTS-DOCUMENTATION.html#interaction-ranking-scoring-module). The value range for this score is 0-100. Please let me know if this is not what you were asking about.

Best,

Robert.

**Comment by Pedramto89** [comment]
Thank you Robert for your quick response! That document is really helpful. I have to read it thoroughly. If I had any questions, will ask.
Best,
Pedram
