### ISSUE TITLE
Missing CellSign_active_interactions and CellSign_active_interactions_deconvoluted files when running Method2

### ISSUE THREAD

**Issue by wfaalajr** [ventolab/CellphoneDB#156]
Hi! I am currently using CellphoneDB v5 and database v5. I noticed that the final output dictionary cpdb_results contains all the output as mentioned in the tutorial:

`list(cpdb_results.keys())`

Gives:

['deconvoluted',
 'deconvoluted_percents',
 'means',
 'pvalues',
 'significant_means',
 'CellSign_active_interactions',
 'CellSign_active_interactions_deconvoluted',
 'interaction_scores']

But when I check my output directory, the files for CellSign_active_interactions and CellSign_active_interactions_deconvoluted are not there. Has this happened to anyone?

**Comment by winglet0996** [comment]
@wfaalajr @datasome 
Hi! I met the same issue in running method 3 original ipynb tutorial. The CellSign module outputs are literally empty ...

**Comment by wfaalajr** [comment]
@winglet0996 yeah XD i guess it’s important for some applications (e.g. to verify transcriptional activation of downstream genes) in which case supplying the TFs file is necessary..but the format of the file is too bothersome to make (i’m just lazy i guess). just do the qPCR and be done with it.
