### ISSUE TITLE
bug report with newest numpy and pandas.

### ISSUE THREAD

**Issue by QqQss** [ventolab/CellphoneDB#17]
When using NumPy-1.21.2 and Pandas-1.3.4, a slicing-like error will be raised during "**Launching Method cpdb_statistical_analysis_launcher**" process.

This error will disappear if I return to numpy-1.19.5 and pandas-1.1.4.

**Comment by prete** [comment]
Hi @QqQss indeed those versions you first mention are not supported by CellPhoneDB. As per the [requirements](https://github.com/ventolab/CellphoneDB/blob/master/requirements.txt) it needs numpy<=1.19.5 and pandas<1.1.4.
