### ISSUE TITLE
KeyError: 'LAMA3_integrin_a3b1_complex' when running cpdb_statistical_analysis_method.call

### ISSUE THREAD

**Issue by VittoriaDBocchi** [ventolab/CellphoneDB#185]
HI! Thank you for developing this tool.
I tried to run cpdb_statistical_analysis_method.call as follows 
![image](https://github.com/ventolab/CellphoneDB/assets/120423622/6b6ad814-c6b8-4815-a8e4-d4bcbb563e54)
However when getting to this step:
# Step 5: calculate the ligand-receptor score.
--> 344 interaction_scores = score_product(matrix=cpdb_fms,
                                    means=means,
                                 separator=separator,
                                  interactions=interactions,
                                  id2name=id2name,
                                  threads=threads)
 return interaction_scores

I get this error KeyError: 'LAMA3_integrin_a3b1_complex' 

I am not if this is a problem of the database or my data but not sure how to solve this.
Thank you so much in advance for your help.
All the best,
Vittoria

**Comment by VittoriaDBocchi** [comment]
I think this happens specifially when I add "score_interactions = True"

**Comment by cakirb** [comment]
Hi @VittoriaDBocchi,

This error (also reported at #176) happens when the counts are not in the correct format, could you please make sure that they are log-normalised without z-scaling so the zeros won't be transformed?

Best,
Batu

**Comment by VittoriaDBocchi** [comment]
Thank you so much!!

**Comment by cakirb** [comment]
Hi @VittoriaDBocchi,

Assuming your problem has been fixed, I'm closing this issue. Feel free to reopen it if the same problem persists.

Best,
Batu
