### ISSUE TITLE
Are all cellphonedb database v2.0.0 identical

### ISSUE THREAD

**Issue by JanLeipzig** [ventolab/CellphoneDB#20]
Hi,

unfortunately I'm a bit confused with the introduction of "CellPhoneDB v3". On the github page "Database update WNT pathway has been further curated." is mentioned as new in cellphonedb v.3.0.0.

Using an older version of cellphonedb (2.1.7), gives the following information:
'cellphonedb database list_remote'
version v2.0.0 *latest: released: 2019-06-21T19:55:09Z, url: https://github.com/Teichlab/cellphonedb-data/releases/tag/v2.0.0, compatible: True

The newest version of cellphonedb (3.0.0, from ventolab), says:
'cellphonedb database list_remote'
version v2.0.0 *latest: released: 2021-12-21T17:09:48Z, url: https://github.com/ventolab/cellphonedb-data/releases/tag/v2.0.0, compatible: True

**Question:** 
Are the "version v2.0.0 *latest: released: 2019-06-21T19:55:09Z" and "version v2.0.0 *latest: released: 2021-12-21T17:09:48Z" identical as the version number indicates?

Additional comment:
Even if both databases are identical I don't think you should have identical version numbers with different release dates. So they should either have the same release date or the same version number but not both. 
It would be much less confusing if the cellphonedb database version numbers are independent from the cellphonedb software version numbers. I'm not sure if this is the case at the moment or not.

**Comment by prete** [comment]
Starting from [CellphoneDB v3.0.1](https://pypi.org/project/CellPhoneDB/3.0.1/) you'll get the new database using the python package or download it with `cellphonedb database download` (only for clientes +3.0.1)
