### ISSUE TITLE
Errors arose when installing cellphonedb==5.0.0

### ISSUE THREAD

**Issue by Jessica1525809** [ventolab/CellphoneDB#200]
Hi @ktroule ,
When I tried to install the cellphonedb package, the following error arose:
<img width="866" alt="截屏2024-08-05 20 27 37" src="https://github.com/user-attachments/assets/2f84cf11-45d1-4caf-8221-de7cb5f53fcf">

I used 'pip install cellphonedb==5.0.0' and my internet connection had no problem.

I would appreciate it if you could help me.

Thank you!

**Comment by ktroule** [comment]
Try
`pip install cellphonedb`
It should install version 5.

**Comment by Jessica1525809** [comment]
> 尝试它应该安装版本 5。`pip install cellphonedb`

Thank you for your kind reply. It was a python version incompatibility. The problem was solved after updating the python version.
