### ISSUE TITLE
Some clusters/cell_types in DEGs are not present in metadata potential bug?

### ISSUE THREAD

**Issue by RunyuXia** [ventolab/CellphoneDB#204]
Hi! I’m encountering the following error:

Exception: Some clusters/cell_types in DEGs are not present in metadata.

I double-checked that ~age_up.iloc[:, 0].isin(age_meta.iloc[:, 0]) is returning False, but the error still persists. Could you help me solve the problem? Thank you!

After looking at the source code, it seems that when reading the DEG data, the first column is not being read as the index. I saved the DEG data with the first column as cell types and the second column as upregulated genes, as described in the tutorial. However, since multiple genes can be upregulated for a single cell type, I could not set the cell type as the index because indexes cannot have duplicates. As a result, the dataframe after reading contains three columns, with the first column as the original index and the other two columns. According to the code, only the first two columns are retained, which might be causing the issue.

[age_meta.csv](https://github.com/user-attachments/files/17326238/age_meta.csv)

[age_up.csv](https://github.com/user-attachments/files/17326719/age_up.csv)

**Comment by ktroule** [comment]
Hi.

Your input file seems to contains three columns, the index should not be saved in the file.
```
,cell_type,gene
0,B_cell,B3gnt2
1,B_cell,Cpne1
2,B_cell,Ube2v1
3,B_cell,A930011G23Rik
4,B_cell,Nt5e
5,B_cell,Timm23
6,B_cell,Gng10
7,B_cell,Rab4b
```

Regards
