### ISSUE TITLE
pvalues.txt outputting binary results

### ISSUE THREAD

**Issue by rs-hunter** [ventolab/CellphoneDB#21]
Hi,

I'm trying to generate dotplots using the pvalues.txt and means.txt files output by the statistical_analysis method. However, the output of the pvalues file appears to be a binary result rather than a p-value. I've attached one of the outputs here: [pvalues.txt](https://github.com/ventolab/CellphoneDB/files/8288771/pvalues.txt)
Is anyone else experiencing this issue? I saw a closed issue with the same concern but the poster turned out to be mistaken, so maybe it's a problem with the files I'm providing. Any suggestions would be appreciated!

Thanks,
RH

**Comment by luzgaral** [comment]
Dear [rs-hunter](https://github.com/rs-hunter),

Can you provide your cellphonedb run?

Thank you

**Comment by rs-hunter** [comment]
Here it is:
cellphonedb method statistical_analysis naive_meta.txt naive_counts.txt
[ ][APP][15/03/22-10:23:30][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][15/03/22-10:23:30][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][15/03/22-10:23:30][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][15/03/22-10:23:30][INFO] Using custom database at /Users/rahelhunter/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][15/03/22-10:23:30][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][15/03/22-10:23:30][INFO] Launching Method _set_paths
[ ][APP][15/03/22-10:23:30][WARNING] Output directory (/Users/rahelhunter/out) exist and is not empty. Result can overwrite old results
[ ][APP][15/03/22-10:23:30][INFO] Launching Method _load_meta_counts
[ ][APP][15/03/22-10:24:49][INFO] Launching Method _check_counts_data
[ ][CORE][15/03/22-10:24:49][INFO] Launching Method cpdb_statistical_analysis_launcher
[ ][CORE][15/03/22-10:24:49][INFO] Launching Method _counts_validations
[ ][CORE][15/03/22-10:24:49][INFO] Launching Method get_interactions_genes_complex
[ ][CORE][15/03/22-10:24:50][INFO] [Cluster Statistical Analysis] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:4 Precision:3
[ ][CORE][15/03/22-10:24:52][INFO] Running Real Analysis
[ ][CORE][15/03/22-10:24:52][INFO] Running Statistical Analysis
[ ][CORE][15/03/22-11:40:43][INFO] Building Pvalues result
[ ][CORE][15/03/22-11:40:43][INFO] Building results

**Comment by luzgaral** [comment]
According to your [pvalues.txt](https://github.com/ventolab/CellphoneDB/files/8288771/pvalues.txt), you only have ONE celltype and cellphone is only checking interactions within this celltype (`dmm10k|dmm10k`). 

CellphoneDB statistical_analysis is designed to work with multiple celltypes.

**Comment by rs-hunter** [comment]
Got it - thank you!

**Comment by raman91** [comment]
Hi, I have multiple celltypes, but still getting binary p-values :(
Could you explain why it could be possible? Thank you

**Comment by raman91** [comment]
[pvalues.txt](https://github.com/ventolab/CellphoneDB/files/10382403/pvalues.txt)
Here, is my file for your reference. Thanks

**Comment by raman91** [comment]
Is it because of --pvalue (Pvalue threshold) option?
