### ISSUE TITLE
Can not set --result-precision was other number

### ISSUE THREAD

**Issue by Zejian-Wang** [ventolab/CellphoneDB#24]
Hi Team,

I was used newest cellphonDB, and found I cound't get specific p-value number in pvalues.txt.

The reason of get specific p-value number is I want to do FDR-adjusted for result p-value.

When I set --result-precision=8, all p-values lower than 0.01 were "0.0", however number in other files such as "significant_means.txt" will changed by “--result-precision” setting.

I changed the number in 636 line of */cellphonedb/src/core/methods/cpdb_statistical_analysis_helper.py

     "significant_mean_rank = significant_mean_rank.round(3)" to "significant_mean_rank = significant_mean_rank.round(8)"

Unfortunately nothing changed after I re-run it.

The command I used:
"cellphonedb method statistical_analysis input.txt Expression_matrix.txt --threads 10 --threshold 0.1 --output-path ./out --counts-data hgnc_symbol --result-precision 8"

Are there any things I can do to get more specific p-value number? 

Thank you,

Sincerely,
Zejian

**Comment by datasome** [comment]
Hi Zejian,
The latest released version of CellphoneDB (https://pypi.org/project/CellphoneDB/) reports p-values with 3 decimal places precision. I suggest you use the latest version instead. Please note that the recommended way of running the tool has changed - from version 4.0.0 no command line interface is offered - the users are encouraged to run the tool via Jupyter notebooks.
Best regards,
Robert
