### ISSUE TITLE
Downloading Database

### ISSUE THREAD

**Issue by sylvia-science** [ventolab/CellphoneDB#28]
I'd like to check if a pair of genes is present in the database. I've tried running the cellphonedb database download command but I'm not sure where the data has been downloaded since it's not in my local folder. How do I get access to the database?

**Comment by JanLeipzig** [comment]
According to the manual (https://github.com/ventolab/CellphoneDB):
Downloaded versions will be stored in a user folder under ~/.cpdb/releases

**Comment by prete** [comment]
Hi @sylvia-science, `cellphonedb database download` will download new releases to `~/.cpdb/releases` like @JanLeipzig  mentioned, and `~` expands to your home folder. So:
- mac: `/User/sylvia/.cpdb/releases`
- unix: `/home/sylvia/.cpdb/releases`
- win: `C:\users\sylvia\.cpdb\releases`
