### ISSUE TITLE
Using raw or Normalized counts ?

### ISSUE THREAD

**Issue by anidj** [ventolab/CellphoneDB#31]
Hi,

I am a bit confused regarding the counts file that we should provide to CellphoneDB.
This tutorial [https://www.cellphonedb.org/faq-and-troubleshooting](url) uses the normalized counts data (for CellphoneDB v2) and this tutorial: [https://github.com/ventolab/CellphoneDB/blob/master/notebooks/0_prepare_your_data_from_Seurat.ipynb](url) uses the raw counts (for CellphoneDB v3), however, when I look at the count file, it looks normalized.  Should we use the raw or the normalized counts ?

Thanks a lot for your help,

Best,

**Comment by luzgaral** [comment]
Hi,

For the `cellphonedb method statistical_analysis` method, we recommend you to use normalised counts. For `cellphonedb method degs_analysis`, it does not matter whether these are raw or normalised.

I've fixed the v3 tutorial so that everything points to normalised counts.

Thank you,

Luz
