### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by brianpenghe** [ventolab/CellphoneDB#34]
![image](https://user-images.githubusercontent.com/4110443/168790948-b79cad3d-67e3-4701-ba3b-6641db40c352.png)

I was uploading a list of receptors and ligands but this page showed up.
Could you fix this issue?

**Comment by prete** [comment]
Hi @brianpenghe the list may be too long for the website. You can try getting the same information but using the python package. Let's say your elements are: FAS,TNF,FASLG,FAS,TNFSF13B,CD40, you can do this:

```bash
cellphonedb query find_interactions_by_element FAS,TNF,FASLG,FAS,TNFSF13B,CD40 --output ligand_receptor_interactions.csv
```

Results will be saved to `ligand_receptor_interactions.csv`
