### ISSUE TITLE
Negative indices error when using h5ad generated from dgCMatrix

### ISSUE THREAD

**Issue by jachou1** [ventolab/CellphoneDB#37]
Hello. I was able to convert a dgCMatrix into a Seurat object, and finally a h5ad object using the R package sceasy. 

I was able to run the statistical method on it until it threw this error of negative indices.
<img width="983" alt="Screen Shot 2022-05-19 at 10 19 45 PM" src="https://user-images.githubusercontent.com/88116657/169435965-7e138f77-eee7-4845-95bb-fd145984c88d.png">

I don't understand what the source of the problem is: where are the negative indices found? Could someone point me in the right direction to figure this out?

Thanks.

**Comment by huzhimaye** [comment]
Hi

Not a member of the dev team but hopefully this can be helpful:

I met the same error as you, inspired by #32, I checked the meta file and found 'NA' there. After these NA were modified, I'm able to run the method.

**Comment by luzgaral** [comment]
Hi jachou1,

Were the NA causing this error?

Thank you,

Luz
