### ISSUE TITLE
the total number of significant interactions and mean values when comparing the results from more than one sample

### ISSUE THREAD

**Issue by cjhong** [ventolab/CellphoneDB#38]
Thank you for such a great analysis pipeline!

There are two scRNA-seq samples, A and B. CellphoneDB (cpd) ran on A and B. The total number of significant interactions in A is larger than B. I am curious to know if the total number of significant interactions is independent of the input number of cells. Also, what about the mean value? I have many samples that can be split into two groups. I am considering a method to compare between cpd results of the two sample groups. Any suggestion will be great! Thank you!

**Comment by luzgaral** [comment]
Hi,

Results should be consistent to sample size. You might want to test if this holds true for your dataset with downsampling.


Best,

Luz
