### ISSUE TITLE
from R Seurat: log-normalized values @data, rather than @counts?

### ISSUE THREAD

**Issue by forecast1216** [ventolab/CellphoneDB#40]
Thank you for CellPhoneDB; I admire your work and want to be sure to apply it in a way that is consistent with your vision.  

After reviewing issue #31 (Using raw or normalized counts), I'm still confused, please.  If the intent is to use log-normalized values in CellPhoneDB, then I think that the user would write the (@)data slot from the Seurat object, rather than the (@)counts slot as shown in the notebook at https://github.com/ventolab/CellphoneDB/blob/master/notebooks/0_prepare_your_data_from_Seurat.ipynb.

At https://github.com/satijalab/seurat/issues/2362 , the 12/03/19 a response indicates that, after Seurat normalization, the (@)counts slot continues to contain the raw data, while the (@)data slot contains normalized values.  To support this response, when I normalize the pbmc_small data into a separate object, the (@)counts slots remain the same.

Hence, my picky question of whether I should use the (@)data slot instead of (@)counts.  Thank you very much for answering!

**Comment by apredeus** [comment]
I'll wait for the authors to comment, but I'm pretty sure you're correct: if `@counts` is used, the output contains data that are clearly not normalized.

**Comment by prete** [comment]
Pinging @luzgaral

**Comment by luzgaral** [comment]
Thank you all for noticing. I've fixed this in the notebook.


Best
