### ISSUE TITLE
Error reading files from WriteMM:  no features.tsv

### ISSUE THREAD

**Issue by forecast1216** [ventolab/CellphoneDB#41]
Hello,
When I follow the example at https://github.com/ventolab/CellphoneDB/blob/master/notebooks/0_prepare_your_data_from_Seurat.ipynb to write matrix.mtx, barcodes.tsv, and genes.tsv, then run the cellphonedb command to specify the folder in which I wrote these files, cellphonedb responds with an error that it cannot find the 'features.tsv' file.
Is there a way to work around this error, please?  The header of the matrix.mtx file indicates that it would not be compatible with features.tsv format.
Thank you very much for your splendid work.

**Comment by huzhimaye** [comment]
Just rename genes.tsv to features.tsv

**Comment by luzgaral** [comment]
Thank you both for noticing. I've fixed this in the notebook.

Best

**Comment by forecast1216** [comment]
Thank you!
