### ISSUE TITLE
same-cell-type "specific" interactions?

### ISSUE THREAD

**Issue by ogandril** [ventolab/CellphoneDB#43]
In the Figure 3 of the Efremova paper, there appears some DC1-DC1 interactions.
I am having a very hard time to figure how you can compute a cell type A - cell type A  "specific" interactions by permutations. I would guess that each time you compute the mean value (of either the ligand or the receptor) within the DC1 population it will be exactly the same. There is no "permutation" test possible within the same cell cluster, no? 
As stated in the abstract: "[statistics predicts] enriched cellular interactions between **two** cell types ".
I feel like I am missing something here...

**Comment by luzgaral** [comment]
Hi,

CellphoneDB also looks at self-interactions.

CellphoneDB permutes **the cell to cluster assignment** for all the cells, therefore it can estimate a p-value for all clusters/celltypes.  If both L and R are highly specific to the same cell type, the p-value for the self-interaction will be significant. 

Best,

Luz

**Comment by ogandril** [comment]
Ah OK, I see, you always perform permutations between at least two clusters, but both L and R can be enriched in one of the two. Makes sense. Thank's!
