### ISSUE TITLE
Difference between `gene_name` and `hgnc_symbol`?

### ISSUE THREAD

**Issue by apredeus** [ventolab/CellphoneDB#44]
Hello CellphoneDB team, 

Documentation lists the following option for gene identifiers:

> --counts-data: [ensembl | gene_name | hgnc_symbol] Type of gene identifiers in the counts data

Which one is the default, does the tool try to auto-detect, and what is the difference between `gene_name` and `hgnc_symbol`? 

Thank you!

**Comment by prete** [comment]
Hi @apredeus The default is ensembl. The tool doesn't automaticaly detect the input gene type, you need to provide it explicitly if you want to work with something other than ensembl. Regarding the difference between `gene_name` and `hgnc_symbol`, both are the same but are kept for legacy reasons.

**Comment by apredeus** [comment]
Thank you Martin!
