### ISSUE TITLE
Cannot find interaction in annotated db

### ISSUE THREAD

**Issue by parkjooyoung99** [ventolab/CellphoneDB#46]
I was trying to find more information about this interaction so I have visited InnateDB (https://www.innatedb.com/index.jsp) but could not find this interaction. i wonder if our interaction.csv is well updated.
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/77565848/176675580-1f064adb-745c-4ecf-944f-7e455bb2de06.png">

Also, i wonder with what rationale have you annotated some interactions. 

Thank you :)

https://www.innatedb.com/interactionSearch.do?listType=interaction&participantField=idphysical_molecule&participantKeyword=38333&participantKeywordExact=true
https://www.innatedb.com/interactionSearch.do?listType=interaction&participantField=idphysical_molecule&participantKeyword=77290&participantKeywordExact=true

**Comment by luzgaral** [comment]
Hi,
I see HLA-c self interaction here https://www.innatedb.com/interactionSearch.do?listType=interaction&participantField=idphysical_molecule&participantKeyword=77290&participantKeywordExact=true

**Comment by luzgaral** [comment]
Apologies for the late reply.

We retrieved InnateDB-all data from http://www.ebi.ac.uk/Tools/webservices/psicquic/registry/registry?action=ACTIVE#
This seems to be in InnateDB from https://thebiogrid.org/interaction/2263751 

Please, note that we have not curated this interaction, as it does not appear as "**curated**". 

Best,

Luz
