### ISSUE TITLE
no such option: --microenvs

### ISSUE THREAD

**Issue by DanieleMuraro** [ventolab/CellphoneDB#5]
Hi,

I installed cellphonedb with pip3, following the instructions in

https://github.com/ventolab/CellphoneDB/

I can run it with 

cellphonedb method statistical_analysis test_meta.txt test_counts.txt 

but if I include the --microenvs option

cellphonedb method statistical_analysis test_meta.txt test_counts.txt --microenvs test_microenviroments.txt 

I get

Error: no such option: --microenvs

If I then run

cellphonedb --help

I get

Usage: cellphonedb [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  database
  method
  plot
  query

I am wondering if the cellphonedb version I installed via pip3 is old. 
Is there a way I can check? If this is the case, how can I install version 3?
Thank you for your attention.

All the best,

Daniele Muraro

**Comment by luzgaral** [comment]
Hi,

Can you confirm that the version of cellphonedb that you are using is version 3?

Thank you,

Luz

**Comment by DanieleMuraro** [comment]
Hi Luz,

Thank you so much for your reply.
I have just realised that after running

pip3 install cellphonedb

it was actually installed version 2, wheres I thought this command would have installed the latest version.
I installed version 3 (specifying the version in pip3) and it's now working.
Apologies for disturbing you on this issue.

Best,

Daniele
