### ISSUE TITLE
Issue installing cellphoneDB on macOS

### ISSUE THREAD

**Issue by nadiacneto** [ventolab/CellphoneDB#50]
Hi team,

I am trying to install cellphone DB on my machine:
macOS Monterey 
Python 3.9.13
pip 22.1.1

`pip install -U cellphonedb
cellphonedb database download`

When I do this I get the following error:
`error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/opt/hdf5@1.8/include -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-12-arm64-3.9/numpy/core/src/umath -Ibuild/src.macosx-12-arm64-3.9/numpy/core/src/npymath -Ibuild/src.macosx-12-arm64-3.9/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-12-arm64-3.9/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -Ibuild/src.macosx-12-arm64-3.9/numpy/core/src/common -Ibuild/src.macosx-12-arm64-3.9/numpy/core/src/npymath -c numpy/core/src/multiarray/array_assign_scalar.c -o build/temp.macosx-12-arm64-cpython-39/numpy/core/src/multiarray/array_assign_scalar.o -MMD -MF build/temp.macosx-12-arm64-cpython-39/numpy/core/src/multiarray/array_assign_scalar.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1`
  
`note: This error originates from a subprocess, and is likely not a problem with pip.`
`  ERROR: Failed building wheel for numpy`
`Failed to build scikit-learn numpy`
`ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects`

I am able to locate numpy on my machine:
`pip3 show numpy`
Name: numpy
Version: 1.23.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: 
Required-by: scikit-learn, scipy

Please let me know if I am missing any other dependency or if there's anything else I should be doing beforehand. 
Thank you kindly for your help

**Comment by prete** [comment]
Hi @nadiacneto the command for installing (or updating) CellPhoneDB is:
`pip3 install -U cellphonedb`

only after the install has completed you need to download the latest database with:
`cellphonedb database download`

Can I check you are actually running both commands separately?

I'm going to guess that you're running this on an M1 Mac laptop, those devices have shown issues while installing older versions of some packages. In this case, the needed numpy version is 1.19.5 and may no be compatible with your architecture/compiler. However, if you've already got the requirements installed, then you may want to try installing CellPhoneDB without dependencies using:
```
pip3 install --no-dependencies cellphonedb
```

keep in mind that running cellphonedb will only work if you've got [the dependencies](https://github.com/ventolab/CellphoneDB/blob/master/requirements.txt) installed on your own.

**Comment by nadiacneto** [comment]
Hi @prete 

I was indeed running the single command to install cellphone db.
`pip3 install -U cellphonedb`

Seems like you are correct and I am on a M1 Mac machine and when trying to install numpy v 1.19.5 I get the below error 
`ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects`

Has anyone with a similar machine as mine successfully managed to install cellphoneDB?

**Comment by sinanugur** [comment]
Hi @nadiacneto 

I was able to install it into M1 Mac. Here is how:

```
conda create -n cellphone
conda activate cellphone
conda config --show (make sure your environment is osx64 note arm64, arm64 fails when installing)
conda install python=3.7
conda install r-base -c r
pip install cellphonedb
```

Cheers,

**Comment by prete** [comment]
@nadiacneto hope @sinanugur answer worked for you, otherwise you can try with other solutions for M1/m2 devices discussed in #76
