### ISSUE TITLE
Error when subsetting with selected rows and cols

### ISSUE THREAD

**Issue by garfieldyc** [ventolab/CellphoneDB#51]
Hi, thank you for developing this wonderful tool. I have encountered an error when trying to dot plot selected rows and cols using the following script.
cellphonedb plot dot_plot --rows in/rows.txt --columns in/columns.txt

It showed Error: Invalid value for '--rows': File 'in/rows.txt' does not exist. It seems rows.txt and columns.txt files are not in the correct directory. I am wondering where these two files should be placed. 

Thank you,

**Comment by prete** [comment]
Hi @garfieldyc, thank you for using CellPhoneDB. 

Can tou confirm if `rows.txt` and `columns.txt` are actually inside the `in` folder you mention?

If you've cloned the repository and you're trying to run the examples keep in mind that the paths for those is
[`in/example_data/`](https://github.com/ventolab/CellphoneDB/tree/master/in) from the base path `CellphoneDB` where the repository was cloned.

**Comment by garfieldyc** [comment]
> Hi @garfieldyc, thank you for using CellPhoneDB.
> 
> Can tou confirm if `rows.txt` and `columns.txt` are actually inside the `in` folder you mention?
> 
> If you've cloned the repository and you're trying to run the examples keep in mind that the paths for those is [`in/example_data/`](https://github.com/ventolab/CellphoneDB/tree/master/in) from the base path `CellphoneDB` where the repository was cloned.

Thank you for your reply. It works now.
