### ISSUE TITLE
CellPhoneDB v4 absent in the repository

### ISSUE THREAD

**Issue by polinaderev** [ventolab/CellphoneDB#52]
Dear CellPhoneDB developers,

in the README.md file, version from July 18, 2022 (currently the newest one), you mention CellPhoneDB version 4. You invite users to use it by updating cellphonedb and downloading the new database:
```
pip install -U cellphonedb
cellphonedb database download
```

However, when I check the [release history ](https://pypi.org/project/CellPhoneDB/#history)on PyPI, the latest version I can see there is 3.1.0. 

I also fail to update my cellphonedb to a version higher than 3.1.0:
```
(cpdb) [pderevianko@n0043 software]$ pip install -U cellphonedb
```

```
Requirement already satisfied: cellphonedb in /hpc/local/CentOS7/pmc_heidenreich/software/anaconda3/envs/cpdb/lib/python3.7/site-packages (3.1.0)
```
and a bunch of other, 'Requirement already satisfied.'

I can see that after downloading the new database, my database has a version number 4.0.0:
```
(cpdb) [pderevianko@hpcs04 software]$ cellphonedb database list_local
version v4.0.0 *latest
version v2.0.0
```
However, my cellphonedb software is still v3.1.0:
```
(cpdb) [pderevianko@hpcs04 software]$ pip show cellphonedb
Name: CellPhoneDB
Version: 3.1.0
Summary: Inferring cell-cell communication
Home-page: https://cellphonedb.org
Author: TeichLab/VentoLab
Author-email: contact@cellphonedb.org
License: MIT
Location: /hpc/local/CentOS7/pmc_heidenreich/software/anaconda3/envs/cpdb/lib/python3.7/site-packages
Requires: anndata, boto3, click, flask, Flask-RESTful, Flask-Testing, geosketch, h5py, numpy, numpy-groupies, pandas, pika, PyYAML, requests, rpy2, scikit-learn, SQLAlchemy, tqdm
Required-by:
(cpdb) [pderevianko@hpcs04 software]$
```
Is it normal that the software version 4.x.x is absent in the repository and database version 4.0.0 is used with the software version 3.1.0?

**Comment by prete** [comment]
Hi @polinaderev, thank you for using CellPhoneDB.
`CellPhoneDB version 4` refers to the v4 of the *database* not the python package. 
The package version was bumped to a minor version only because algorithms remain largeyl the same as in v3, the main change was the new release of curated data.

**Comment by polinaderev** [comment]
Alright, thanks a lot!

**Comment by zerpiko** [comment]
Hi, apologies for reopening this thread. I suggest adding this explanation to the README file as it can catch some people off guard (certainly my case).
