### ISSUE TITLE
[ERROR] Invalid Counts data

### ISSUE THREAD

**Issue by nadiacneto** [ventolab/CellphoneDB#55]
Hi cellphonedb team,

I have generated all the input files for cellphonedb using your tutorial https://github.com/ventolab/CellphoneDB/blob/master/notebooks/0_prepare_your_data_from_Seurat.ipynb
I have mouse data that I successfully converted to their human orthologs. My original input was seurat.

However I am getting the following error, after checking all my files I am unsure what the issue could be:
cellphonedb method degs_analysis cellphonedb_meta.txt cellphonedb_count.txt DEGs.txt --counts-data hgnc_symbol
[ ][CORE][04/08/22-19:19:57][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][04/08/22-19:19:57][INFO] Using custom database at /home/ubuntu/.cpdb/releases/v4.0.0/cellphone.db
[ ][APP][04/08/22-19:19:57][INFO] Launching Method cpdb_degs_analysis_local_method_launcher
[ ][APP][04/08/22-19:19:57][INFO] Launching Method _set_paths
[ ][APP][04/08/22-19:19:57][INFO] Launching Method _load_meta_counts
[ ][APP][04/08/22-19:49:36][INFO] Launching Method _check_counts_data
[ ][APP][04/08/22-19:49:36][INFO] Launching Method _load_degs
[ ][CORE][04/08/22-19:49:36][INFO] Launching Method cpdb_degs_analysis_launcher
[ ][CORE][04/08/22-19:49:36][INFO] Launching Method _counts_validations
[ ][APP][04/08/22-19:49:38][ERROR] Invalid Counts data: Some cells in meta did not exist in counts. Maybe incorrect file format.[ ][APP][04/08/22-16:49:33][ERROR] Invalid Counts data: Some cells in meta did not exist in counts. Maybe incorrect file format.

This is a head of my meta.tsv file
![image](https://user-images.githubusercontent.com/103027246/182934089-34592db0-0478-45e2-878d-daeeb23bad6e.png)

This is a head of my DEG file
![image](https://user-images.githubusercontent.com/103027246/182934366-aa35ef73-1c68-4ce8-adac-eee246089a15.png)

This is a head of counts file
![image](https://user-images.githubusercontent.com/103027246/182934304-700c6d1c-e9f1-4936-985f-3709a98eded1.png)

Thank you kindly

**Comment by prete** [comment]
Hi @nadiacneto, you should check if all the Cells (elements on the first column) in your `cellphonedb_meta.txt` file have a matching cell in the headers of `cellphonedb_count.txt`. If that's not the issue then you can share your files here and we can have a look.

**Comment by nadiacneto** [comment]
That's not the issue, all the cells match the counts and the meta. Do you have a support email to which I could share the files privately? 
Thank you

**Comment by prete** [comment]
You can use the [contact form on cellphonedb.org](https://www.cellphonedb.org/contact-us) or `contact@cellphonedb.org` and that will go to the team. 

Alternatively, you can use the email on my GitHub profile to get the files directly to me.

**Comment by nadiacneto** [comment]
Hi @prete 
I did manage to figure out what's the issue. Seems like when extracting the counts from a seurat object you get a sparse matrix. That needs to be converted to a dense matrix, once that was done cellphonedb ran just fine. 
Thanks so much!!

**Comment by prete** [comment]
Glad to read you solved it. Thank you for letting us know.

**Comment by jinlanzhan** [comment]
> Hi @prete I did manage to figure out what's the issue. Seems like when extracting the counts from a seurat object you get a sparse matrix. That needs to be converted to a dense matrix, once that was done cellphonedb ran just fine. Thanks so much!!

I have encountered the same problem. Could you describe in detail how you solved it?

**Comment by nadiacneto** [comment]
Hi @jinlanzhan,
I was using R for my project and you can load your counts file and convert counts <- as.matrix(counts). Check that all your rownames and colnames are preserved.
