### ISSUE TITLE
Unable to download CellPhoneDB

### ISSUE THREAD

**Issue by clb94** [ventolab/CellphoneDB#57]
Hello,

I'm having trouble starting the pipeline to process my scRNAseq data with CellPhone DB. I am working in the Jupyter Notebook with Python version 3.9, on an M1 Macbook Pro. Firstly, I am unable to create an environment using conda; I type **conda create -n cpdb python=3.9**, and am then asked to confirm installation of required packages. When I type and enter [y], the code is stuck and runs indefinitely. This I understand isn't a problem with CellPhone DB but gives some context.

I therefore tried to directly install the CellPhoneDB package with: **pip install -U cellphonedb**. 
A lot of code is printed but it contains some errors, notably that the scikit_learn kit couldn't be built. I have tried installing cellphone db without dependencies (as suggested on this thread https://github.com/ventolab/CellphoneDB/issues/50), but I am unable to install the required version of scikit_learn listed following this advice (0.22) (https://github.com/ventolab/CellphoneDB/blob/master/requirements.txt). 

I assume that the package hasn't properly installed, because when I follow the next instruction and type: **cellphonedb database download**, a SyntaxError is returned. 

If anyone could offer any advice so that I may move forward, I would be really grateful. I am also happy to provide more information if that is relevant - this language is new to me so apologies if I have missed something vital. Thank you!

**Comment by clb94** [comment]
Thanks so much for getting back to me.

Sorry, but I don't quite understand (python is super new to me!). I have been running the code on the Jupyter Notebook, which I launch from the Anaconda Navigator which I downloaded from the Anaconda distribution website. I don't seem to have access to another python terminal, or at least not one I can find. I tried to type **uname -m** into the Jupyter notebook but it errored and said that uname was not defined so I guess this is meant for another interface which I haven't grasped. I tried to install Rosetta2 from Jupyter Notebook with pip install but this couldn't be found, so again I must be in the wrong place. In addition, I do not know how to downgrade the version of Python which the Anaconda Navigator runs off of, which is how I launch the notebook.

This must seem very basic, but if you have any really simple instructions on another way to launch an environment and try this code I would be very grateful as I think I must be doing something fundamentally wrong at step one. Thank you!

**Comment by clb94** [comment]
> Hi @clb94, thank you for using CellPhoneDB.
> 
> We've seen lots of M1/M2 MacBooks issues lately in general with Python installs for all packages, not just CPDB.
> 
> Can I check:
> 
> * is rosetta2 is enabled on your terminal by doing `uname -m` (do you get x86_64 or arm64?)
> * which conda installer you used? I guess you used [this one](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh), but if you're using the intel version you need to have [Rosetta2](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment) installed
> 
> Finally, for CellPhoneDB we recomend python 3.8 rather than 3.9.
> 
> Hope any of those things help oyu move forward.

Thanks so much for getting back to me. To answer your questions, I get arm64 when I look in terminal. Just in case, I installed rosetta2 which was successful. 

I used the miniconda3 package, for the apple M1 arm. This also does state that this is running the recommended python 3.8 rather than 3.9, and I have deleted anaconda navigator to remove any confusion. 

I then installed jupyter in the terminal, and launched the jupyter notebook from there. Following the instructions on this page, I tried to generate a virtual environment by both conda and python methods (don't know if this is necessary in jupyter) but each of these failed - either because it says I am not using conda, or a syntax error. I then went straight to the installation step of CellPhoneDB, which seemed to work. However, once again when I type **cellphonedb database download**, it returns a syntax error and I am unable to continue.

Thank you so much for your assistance. Please let me know if you can think what the problem might be.

**Comment by dacheampong** [comment]
Any update on this as I am also having similar issues installing it on M1 macbook pro, python 3.8, I do have rosetta 2 enabled with anaconda installer but still unable to get cellphonedb installed in my environment.

**Comment by L-wang17** [comment]
Any update on this? I have M1 chip with arm64 and similar issue installing the CellphoneDB through conda. I had error "fail for building scikit-learn" and I tried the way that scikit-learn recommend for M1 separately and then install CellphoneDB I got same error. Is there a way to solve that?

**Comment by datasome** [comment]
Hi L-wang17,

I work on a 64bit M1 chip mac so hopefully we will be able to sort this together. 
Assuming that 
1. You already have a terminal open in x86_64 architecture  (see https://apple.stackexchange.com/questions/428768/on-apple-m1-with-rosetta-how-to-open-entire-terminal-iterm-in-x86-64-architec), 

2. Could you please follow instructions on https://towardsdatascience.com/how-to-install-miniconda-x86-64-apple-m1-side-by-side-on-mac-book-m1-a476936bfaf0 to download and install miniconda, and then do:

3. conda create -n cpdb python=3.8
4. source activate cpdb
6. pip install -U CellphoneDB==3.1.0 (I'm assuming you're after using the old version of CellphoneDB, but if you're happy to use the latest version, please try: pip install -U cellphonedb)

.. and let me know how you got on? The above has worked for me (at least for the latest version of CellphoneDB: 4.0.0)

Best,

Robert.
