### ISSUE TITLE
New interactions

### ISSUE THREAD

**Issue by mathewchamberlain** [ventolab/CellphoneDB#58]
Does the v4.0.0 release contain the protein-protein interactions published [in this paper](https://www.nature.com/articles/s41586-022-05028-x)? If not, how can we make that happen?

**Comment by luzgaral** [comment]
Dear @mathewchamberlain 

Thank you for asking!

v4.0.0 release does not contain the protein-protein interactions published in Shilts et al 2022.
We are working on it at the moment and expect to release a new version in September-October.

Best

Luz

**Comment by mathewchamberlain** [comment]
Thanks Luz, do you mind leaving this issue open and then closing it once you've performed the update?

Best regards,

Mathew
