### ISSUE TITLE
Can't build Docker Image from Dockerfile

### ISSUE THREAD

**Issue by johnjeang** [ventolab/CellphoneDB#61]
Hello, 

I tried to build a Docker image using the provided Dockerfile in this repository but I got the following error 

My command:

```
docker build -t cellphonedb .
```
Error:
```
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Unable to determine R home: [Errno 2] No such file or directory: 'R': 'R'
    Unable to determine R home: [Errno 2] No such file or directory: 'R': 'R'
       Error: rpy2 in API mode cannot be built without R in the PATH or R_HOME defined. Correct this or force ABI mode-only by defining the environment variable RPY2_CFFI_MODE=ABI
      ['cffi>=1.10.0', 'jinja2', 'pytz', 'tzlocal', "packaging;platform_system=='Windows'", 'typing-extensions']
     [end of output]
```

I'm pretty new to Docker, but my understanding is that it should work straight out of the box.  Am I doing something wrong or is this an issue with the Dockerfile?  

Thanks for all your hard work!

**Comment by johnjeang** [comment]
After some reflection I have realized that this Dockerfile is not the appropriate way to use this library.  I have since solved this issue by using a conda environment as suggested by the readme.

**Comment by prete** [comment]
Hi @johnjeang, you're correct. I've updated the Dockerfile ([440ae5a](https://github.com/ventolab/CellphoneDB/commit/440ae5ac000c9c717ba784ae3c656518b4b84a08)) so it's the one that works for building the package.
