### ISSUE TITLE
How many LR interactions annotated in CellphoneDB v4 ? 

### ISSUE THREAD

**Issue by ZheFrench** [ventolab/CellphoneDB#65]
Hi,
Was wondering how many LR interactions CellphoneDB v4 contains now (without complex) ?
From a recent paper from[ DImitrov (Nat Com 2022) ](https://rdcu.be/cW4NT)it seems it's around 2000 LRs ?
Thanks.

**Comment by luzgaral** [comment]
Hi,

Yes, it is around 2,000. 
- Peptidic: 1859 interactions. Note that this number includes not decomposed complexes. If you decompose complexes into individual pairs, this number would be larger.
- Non peptidic: 195 interactions. 

Best

Luz
