### ISSUE TITLE
Why the p values and mean values of clusterA-clusterB are different with the clusterB-clusterA?

### ISSUE THREAD

**Issue by zyan0626** [ventolab/CellphoneDB#7]
Hello! I think it is a great tool!
But I am curious why the p values and mean values of clusterA-clusterB are different with the clusterB-clusterA?
Thank you!

**Comment by luzgaral** [comment]
Hi,

When reading the outputs, is IMPORTANT to note that the interactions are not symmetric. Partner A expression is considered for the first cluster/cell type, and partner B expression is considered on the second cluster/cell type. In other words:

clusterA_clusterB = clusterA expressing partner A and clusterB expressing partner B.
clusterA_clusterB and clusterB_clusterA values will be different.

You will find this information in the [documentation](https://github.com/ventolab/CellphoneDB/blob/master/Docs/RESULTS-DOCUMENTATION.md).

Luz
