### ISSUE TITLE
Output of the DEG method

### ISSUE THREAD

**Issue by sevlandais** [ventolab/CellphoneDB#75]
Hi,

Thank you for developing CellphoneDB.

I was wondering if you can provide a little bit more explanation around how the DEG method works?

1- In the provided description: "This approach will select interactions where all the genes are expressed by a fraction of cells above a --threshold and at least one gene is a DEG", what are "all the genes"? Ligand and receptor?
2- In the output, there is a "relevant_interactions" file. How are the relevant interactions computed?
3- Similarly, in the "significant_means" file, how are the significant means computed?

Thank you,

**Comment by luzgaral** [comment]
Dear @sevlandais 

Thank you for your using cellphoneDB and apologies for the late reply.

Your questions are very pertinent and we hope soon to release a new version of the documentation. Meanwhile, find [here](https://www.cellphonedb.org/documentation) the meaning of the outputs.

Regarding your specific questions:
1. "All the genes in the interaction". If the interaction is composer of L->R1+R2 (where the receptor is a complex of R1+R2), we require L, R1 and R2 to be expressed. This means that L must be expressed in > 10% of the corresponding partner A cells and R1/R2 must expressed in > 10% of the corresponding partner B cells.
2. This file indicates if an interaction is relevant (passes the thresholds) or not. The interaction is relevant (1) if at least one gene in the interaction is a DEG, and all the participants are expressed. Alternatively, the value is set to 0. In the example above, if all L->R1+R2 are expressed int he corresponding cells and any L/R1/R2 is in the differentially expressed genes, then the interaction will be classified as relevant.
3. significant_means will output the means of the interactions that are relevant (1) in the relevant file. 

Best

Luz
