### ISSUE TITLE
How to set up R environment for cellphonedb?

### ISSUE THREAD

**Issue by mxiang1** [ventolab/CellphoneDB#8]
I have the required packages installed in R but am seeing this error message: 

$ cellphonedb plot dot_plot
As there is no R environment set up, some functionalities will be disabled, e.g. plot
You cannot perform this plot command unless there is a working R setup according to CellPhoneDB specs

**Comment by ksaunders73** [comment]
For me I used the terminal in RStudio (bottom left panel next to "console"). Hope this helps!

**Comment by monikaramos** [comment]
@ksaunders73 I tried your suggestion to create an environment with R on it to plot cpdb results but now it is not recognizing the cellphonedb commands. Do I have to call on cellphonedb somehow within the R env or how do I get it to recognize the command. Does it need to be installed again?

**Comment by mxiang1** [comment]
@ksaunders73 Thanks!
@monikaramos I used the plot_dot_by_column_name.R script to directly make the plots in R before seeing @ksaunders73 's comment. You can try that too if nothing else works.

**Comment by ksaunders73** [comment]
@monikaramos I think you have to reinstall it because what I said makes a new virtual environment (that just includes R and python instead of just python). @mxiang1 thanks for pointing out that script! I'll definitely check that out since it's easier to plot stuff in RStudio for me personally

**Comment by prete** [comment]
Quickest way is to get [environment.yml](https://github.com/ventolab/CellphoneDB/blob/master/environment.yml) from the repository and then
```
conda env create --file environment.yml
```
That will create a conda environment (called `cpdb`) with both CellPhoneDB python and R dependencies installed.
