### ISSUE TITLE
is LR results depends on number of cells in each cluster and number of cells per each group

### ISSUE THREAD

**Issue by FADHLyemen** [ventolab/CellphoneDB#81]
HI 
I do not think this is an issue with the package rather than question about the interpretation of the LR results.
I am interested to compare number of interactions between two clusters which they have different number of cells. each cluster have cells from three groups. number of cells from each group in each cluster are different. How accurate to compare number of LR interaction between cluster 1 and cluster 2 in each group if number of cells in both clusters and two groups are different.
for example, can I say, I have more LR between cluster 1 and cluster 2 in group 1 more than group 2 and 3, even number of cells for this group is larger in cluster 1 and 2. shall I do some normalization for number of cells per group before compare number of LR ?
may be this carton help understand my question 
![image](https://user-images.githubusercontent.com/23288387/209396874-517a236b-7b9f-486b-b404-1f95e960f48c.png)

**Comment by luzgaral** [comment]
Hi,

Thank you for using CellphoneDB!

What [method](https://github.com/ventolab/CellphoneDB/blob/master/Docs/RESULTS-DOCUMENTATION.md#analysis-types-in-CellphoneDB) are you using to perform your analysis? Assuming that you are using `statistical_analysis` (method 2), the key is not the number but the proportion of cells from each group. During cell permutation step, if your dataset is heavily biased towards a cell type, then your random reference will be also biased towards the same cell type, thus being harder to find differences. 

**I recommend you to downsample your input in a way that all the celltypes/groups have the same number of cells. If you are to compare celltype1-G1 vs celltype2-G1, your solution 2 is correct.**

Hope this helps,

Luz
