### ISSUE TITLE
Issue while plotting dotplot

### ISSUE THREAD

**Issue by stalware** [ventolab/CellphoneDB#83]
Hello,
I am trying to generate dotplot and heatmap and get the following error. I am not able to get pass this step. The initial results were successfully generated using statistical_analysis
cellphonedb method statistical_analysis --counts-data gene_name meta_table.txt count_matrix.txt 
<img width="1302" alt="Screen Shot 2023-01-03 at 2 34 33 PM" src="https://user-images.githubusercontent.com/36680903/210428430-9f216de2-21a6-4859-9587-9c52c54af381.png">

**Comment by prete** [comment]
Hi @stalware, thank you for using CellPhoneDB. Looks like the version of markupsafe you've got is no compatible with CellphoneDB. Could you please try installing verion 2.0.1 using `pip install -U marksupsafe==2.0.1`?

**Comment by prete** [comment]
closing because it has been inactive for too long
please try the new plotting functions avaiable in cellphonedb >=4.0.0 if you are still having issues
