### ISSUE TITLE
Type of normalisation

### ISSUE THREAD

**Issue by joan-yanqiong** [ventolab/CellphoneDB#84]
Hi, in the doc you mention that normalisation is preferred with an example of that. Does it matter what type of normalisation? I applied the sctransform from Seurat.

**Comment by luzgaral** [comment]
Hi,

Thank you for using CellphoneDB.
Note that [methods 1-2](https://github.com/ventolab/CellphoneDB/blob/master/Docs/RESULTS-DOCUMENTATION.md#analysis-types-in-cellphonedb) of CellphoneDB rely on mean calculation. For the means to be comparable, expression values should have been normalised. You can use your prefered normalisation method.

Hope this helps,
Best.

Luz
