### ISSUE TITLE
How to do differential analysis for cellphonedb result

### ISSUE THREAD

**Issue by xiasijian** [ventolab/CellphoneDB#87]
![image](https://user-images.githubusercontent.com/39158528/218255421-c4742bd6-38d2-47e5-b178-e07682fe0144.png)

(F) Outgoing interactions of TRN subclusters with cancer cells and CD8+ T cells. Top panel: differentially expressed ligands in each subcluster (FDR <0.01, abs.
log2 fold change >1). Heatmap colors clipped at ±3. Bottom panel: respective receptors and the expression by cell type. Dots are only shown for receptors that
are expressed in at least 10% of the respective cell types.

**Comment by luzgaral** [comment]
Hi @xiasijian,

Thank you for using CellphoneDB.
Could you please elaborate  a bit more on your question?
Best,

Luz

**Comment by xiasijian** [comment]
Hello@Luz, Thanks a lot for your reply, the problem I want to ask is how can I differentially analyse the expressed ligands, and get the log2 fold change as the figure show?
best wishes

**Comment by luzgaral** [comment]
Hi @xiasijian,

To get a log fold change, you can use your preferred tool, like Seurat FindMarkers(), DESeq2, limma, or even scanpy.
Please note that CellphoneDB does not uses this information and does not generate the heatmap plot that you mentioned.

We will be updating cellphoneDB and provide more detailed tutorials in the following week. Hope they are of help!

Best,

Luz

**Comment by xiasijian** [comment]
Thanks a lot.



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 6, 2023 21:44 PM
To: ***@***.***&gt;;
Cc: "Sijian ***@***.******@***.***&gt;;
Subject: Re: [ventolab/CellphoneDB] How to do differential analysis forcellphonedb result (Issue #87)




 
Hi @xiasijian,
 
To get a log fold change, you can use your preferred tool, like Seurat FindMarkers(), DESeq2, limma, or even scanpy.
 Please note that CellphoneDB does not uses this information and does not generate the heatmap plot that you mentioned.
 
We will be updating cellphoneDB and provide more detailed tutorials in the following week. Hope they are of help!
 
Best,
 
Luz
