### ISSUE TITLE
Install CellphoneDB fails

### ISSUE THREAD

**Issue by chrsyl** [ventolab/CellphoneDB#88]
With pip install cellphonedb  numpy<=1.19.5,>=1.16.5 is required. Installation fails at my MacBook M2 macosx-11.0-arm64-cpython-310 that uses numpy 1.21. I then installed python 3.9 and tried to install numpy 1.19.2. But then as with the initial cellphonedb install numpy install  fails. 
How to proceed? When will cellphonedb be available for use under  macosx-11.0-arm64?

**Comment by prete** [comment]
Duplica of #76 
Workarounds for M1/M2 arm architectue involve using Rosetta. More info provided by @ktroule here: https://github.com/ventolab/CellphoneDB/issues/76#issuecomment-1477587320
