### ISSUE TITLE
R error dot_plot heatmap

### ISSUE THREAD

**Issue by flyingmonster1** [ventolab/CellphoneDB#89]
Hi developer,
The cellphonedb build in conda virtual environment, but when plot dot_plot, it trigger below error,
I ran `cellphonedb plot heatmap_plot` and `cellphonedb plot dotplot`  but both functions gave out the same error message:

> OSError: cannot load library '"C:\Users\Anaconda3\envs\cpdb\Lib\R"\bin\x64\R.dll': error 0x7e

Would you kindly give any hint on what's going wrong? Thx!

**Comment by Fantasque68** [comment]
Ooops, I also ran into problems while plotting.
It returns the following errors as I executed 

`cellphonedb plot dot_plot`

Error: package or namespace load failed for 'methods':                   
 loadNamespace()里算'methods'时.onLoad失败了，详细内容：                 
  调用: assign(".methodsNamespace", where, baseenv())                    
  错误: cannot add binding of '.methodsNamespace' to the base environment
Error: loadNamespace()里算'methods'时.onLoad失败了，详细内容：           
  调用: assign(".methodsNamespace", where, baseenv())                    
  错误: cannot add binding of '.methodsNamespace' to the base environment
In addition: Warning message:                                            
package "methods" in options("defaultPackages") was not found            
Error: package or namespace load failed for 'datasets':                  
 loadNamespace()里算'methods'时.onLoad失败了，详细内容：                 
  调用: assign(".methodsNamespace", where, baseenv())                    
  错误: cannot add binding of '.methodsNamespace' to the base environment
Error: package or namespace load failed for 'utils':
 loadNamespace()里算'methods'时.onLoad失败了，详细内容：
  调用: assign(".methodsNamespace", where, baseenv())
  错误: cannot add binding of '.methodsNamespace' to the base environment
Error: package or namespace load failed for 'grDevices':
 loadNamespace()里算'methods'时.onLoad失败了，详细内容：
  调用: assign(".methodsNamespace", where, baseenv())
  错误: cannot add binding of '.methodsNamespace' to the base environment
Error: package or namespace load failed for 'graphics':
 loadNamespace()里算'methods'时.onLoad失败了，详细内容：
  调用: assign(".methodsNamespace", where, baseenv())
  错误: cannot add binding of '.methodsNamespace' to the base environment
Error: package or namespace load failed for 'stats':
 loadNamespace()里算'methods'时.onLoad失败了，详细内容：
  调用: assign(".methodsNamespace", where, baseenv())
  错误: cannot add binding of '.methodsNamespace' to the base environment
Error: package or namespace load failed for 'methods':
 loadNamespace()里算'methods'时.onLoad失败了，详细内容：
  调用: assign(".methodsNamespace", where, baseenv())
  错误: cannot add binding of '.methodsNamespace' to the base environment
During startup - Warning messages:
1: package 'datasets' in options("defaultPackages") was not found
2: package 'utils' in options("defaultPackages") was not found
3: package 'grDevices' in options("defaultPackages") was not found
4: package 'graphics' in options("defaultPackages") was not found
5: package 'stats' in options("defaultPackages") was not found
6: package 'methods' in options("defaultPackages") was not found
Error: loadNamespace()里算'methods'时.onLoad失败了，详细内容：
  调用: assign(".methodsNamespace", where, baseenv())
  错误: cannot add binding of '.methodsNamespace' to the base environment
