### ISSUE TITLE
Does it make sense to use CellPhoneDB on mouse data?

### ISSUE THREAD

**Issue by hyjforesight** [ventolab/CellphoneDB#9]
Hello CellPhoneDB,
Thanks for developing this amazing package.
We're wondering whether it's reasonable to use it for mouse data. If so, we can transfer mouse gene names of our data into human's and run, but we're still hesitating because the cell-cell communication is different between mouse and human.
Thanks!
Best,
YJ

**Comment by luzgaral** [comment]
Hello,

You can still use CellPhoneDB translating the gene names to their human orthologs.  In this case, before making any claim, we recommend that you validate (by checking the literature) if the relevant interactions in your results have been observed in mice. We expect conservation between species but there will be exceptions.

Alternatively, you can build a mouse interaction database yourself and use it in CellPhoneDB. Check [generating-user-specific-custom-database](https://github.com/ventolab/CellphoneDB#generating-user-specific-custom-database).

Hope this helps,

Luz

**Comment by hyjforesight** [comment]
Thanks @luzgaral for the information!
