### ISSUE TITLE
Logger parameters lost in this line

### ISSUE THREAD

**Issue by Ericsii** [ventolab/CellphoneDB#90]
https://github.com/ventolab/CellphoneDB/blob/e3d1b4c6407e0e19388565eb97675aa576dcb0ab/cellphonedb/src/database/manager/DatabaseVersionManager.py#L76

I think this line should be

```python
 app_logger.warning(f"Database '{value}' is not available. Trying to download it.")
```

**Comment by datasome** [comment]
Please note that for the current version of CellphoneDB package (the master branch of https://github.com/ventolab/cellphonedb and in https://pypi.org/project/CellPhoneDB/) you need to use data in https://github.com/ventolab/cellphonedb-data/releases/tag/v4.0.0 or earlier. 

https://github.com/ventolab/cellphonedb-data/releases/tag/v4.1.0 is a release candidate for the new version of CellphoneDB package (v4.0.0) that we will be releasing in week or so. The database file format in the new package version (v4.0.0) is not compatible with that in the current package version (3.1.0).

Thank you for your patience with us and apologies for any confusion.
