### ISSUE TITLE
[WARNING] Database '{value}' is not available. Trying to download it

### ISSUE THREAD

**Issue by SerendipityCreate** [ventolab/CellphoneDB#92]
After I downloaded the database and added the environment variables, I still found an error, **“Database '{value}' is not available“**. Then I checked the source code and found that the file 'cellphone.db' was not in the data I downloaded. 

`cpdb_releases = os.environ.get('CELLPHONEDB_RELEASE_PATH', '~/.cpdb/releases')` 
`database_file = 'cellphone.db'`

Did anyone experienced a similar problem and how can I solve it?

**Comment by skye-12138** [comment]
Just found the same error in version v4.1.0, I changed to version V3.0.0(pip install CellPhoneDB==3.0.0), cellphonedb could runs well

**Comment by SerendipityCreate** [comment]
Thank you, that worked

**Comment by Bessyyi** [comment]
I download Database from github (https://github.com/ventolab/CellphoneDB-data) ,then I mv it to /home/ywj/.cpdb/releases/v4.1.0 and unzip it ，then cellphonedb runs well.

**Comment by datasome** [comment]
Please note that for the current version of CellphoneDB package (the master branch of https://github.com/ventolab/cellphonedb and in https://pypi.org/project/CellPhoneDB/) you need to use data in https://github.com/ventolab/cellphonedb-data/releases/tag/v4.0.0 or earlier. 

https://github.com/ventolab/cellphonedb-data/releases/tag/v4.1.0 is a release candidate for the new version of CellphoneDB package (v4.0.0) that we will be releasing in week or so. The database file format in the new package version (v4.0.0) is not compatible with that in the current package version (3.1.0).

Thank you for your patience with us and apologies for any confusion.
