### ISSUE TITLE
subsampling

### ISSUE THREAD

**Issue by jinlanzhan** [ventolab/CellphoneDB#96]

**Comment by ktroule** [comment]
Can we help?

**Comment by jinlanzhan** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7bbc29638b10> in <module>
      2 import glob
      3 import os
----> 4 from cellphonedb.utils import db_utils
      5 db_utils.create_db("/group_homes/public_cluster/home/u37189/Project/20230102_smell_loss/cellphoneDB/out_total_repository/cellphonedb_user_2023-03-09-21_21.db")

ImportError: cannot import name 'db_utils' from 'cellphonedb.utils' (/home/miniconda3/envs/cellphonedb/lib/python3.7/site-packages/cellphonedb/utils/__init__.py)

**Comment by jinlanzhan** [comment]
ImportError: cannot import name 'db_utils' from 'cellphonedb.utils'

**Comment by jinlanzhan** [comment]
![image](https://user-images.githubusercontent.com/122193718/225003974-3859c430-70b4-42ea-8076-93447302eb80.png)
but ,this works well

**Comment by jinlanzhan** [comment]
![image](https://user-images.githubusercontent.com/122193718/225006668-bb080ba8-f32d-43b8-9c86-70a30b067dde.png)

**Comment by ktroule** [comment]
It seems you have installed python 3.7, as noted in the documentation CellPhoneDB requires python 3.8 or higher.
Try again python 3.8.

**Comment by jinlanzhan** [comment]
![image](https://user-images.githubusercontent.com/122193718/225034590-b423db26-c1a8-45d1-b79b-0d59a6983560.png)

thanks, Encountered new problems

**Comment by jinlanzhan** [comment]
> Do you have the `uniprot_synonyms.tsv` in the sources folder?
