### ISSUE TITLE
Some Gene Names Are Missing From Results

### ISSUE THREAD

**Issue by connerlambden** [ventolab/CellphoneDB#99]
Hi, when looking at pvalues.txt, some genes are missing: 

id_cp_interaction | interacting_pair | partner_a | partner_b | gene_a | gene_b
-- | -- | -- | -- | -- | --
CPI-CS0A5B6BD7A | 12oxoLeukotrieneB4_byPTGR1_LTB4R | complex:12oxoLeukotrieneB4_byPTGR1 | simple:Q15722 |   | LTB4R

Any ideas on this?

**Comment by luzgaral** [comment]
Hi @connerlambden 

Gene names for complex complex:12oxoLeukotrieneB4_byPTGR1 are missing because it is a complex, not a single protein/gene. The name of the complex is `12oxoLeukotrieneB4_byPTGR1`.

Hope this helps.

Best

Luz
